services:
  - docker

before_install:
  - echo "SKIPPING TEST BUILD"
  # - docker build -t ankesh/docker-test -f ./client/Dockerfile.dev ./client

script:
  - echo "SKIPPING TEST"
  # - docker run ankesh/docker-test npm test -- --coverage

after_success:
  - docker build -t ankeshnirala/multi-client ./client
  - docker build -t ankeshnirala/multi-nginx ./nginx
  - docker build -t ankeshnirala/multi-server ./server
  - docker build -t ankeshnirala/multi-worker ./worker
  # LOGIN TO THE DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #TAKE THOSE IMAGES AND PUSH THEM TO DOCKER HUVB
  - docker push ankeshnirala/multi-client
  - docker push ankeshnirala/multi-nginx
  - docker push ankeshnirala/multi-server
  - docker push ankeshnirala/multi-worker
